### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by menghuijinxi** [mrkriv/UnrealDotNet#2]
error:
LoginId:a032481a43c98e995017f9b5d05416ef
EpicAccountId:11e66bb96bce4fcb893cd2eaf9133a05

CLR exception - code e0434352 (first/second chance not available)

KERNELBASE
coreclr
coreclr
coreclr
coreclr
coreclr
coreclr
coreclr
coreclr
UE4Editor_UnrealDotNetRuntime!UCoreShell::InvokeInWrapper<char *,0>() [e:\project\c\plugins\unrealdotnet\source\unrealdotnetruntime\public\coreshell.h:101]
UE4Editor_UnrealDotNetRuntime!UCoreShell::LoadCLR() [e:\project\c\plugins\unrealdotnet\source\unrealdotnetruntime\private\coreshell.cpp:87]
UE4Editor_UnrealDotNetRuntime!UCoreShell::UCoreShell() [e:\project\c\plugins\unrealdotnet\source\unrealdotnetruntime\private\coreshell.cpp:43]
UE4Editor_CoreUObject!UClass::CreateDefaultObject() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\class.cpp:2902]
UE4Editor_CoreUObject!UObjectLoadAllCompiledInDefaultProperties() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectbase.cpp:793]
UE4Editor_CoreUObject!ProcessNewlyLoadedUObjects() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\uobjectbase.cpp:867]
UE4Editor_CoreUObject!TBaseStaticDelegateInstance<void __cdecl(void)>::ExecuteIfSafe() [d:\build\++ue4\sync\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:788]
UE4Editor_Core!TBaseMulticastDelegate<void>::Broadcast() [d:\build\++ue4\sync\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:937]
UE4Editor_Core!FModuleManager::LoadModuleWithFailureReason() [d:\build\++ue4\sync\engine\source\runtime\core\private\modules\modulemanager.cpp:510]
UE4Editor_Projects!FModuleDescriptor::LoadModulesForPhase() [d:\build\++ue4\sync\engine\source\runtime\projects\private\moduledescriptor.cpp:540]
UE4Editor_Projects!TryLoadModulesForPlugin() [d:\build\++ue4\sync\engine\source\runtime\projects\private\pluginmanager.cpp:921]
UE4Editor_Projects!FPluginManager::LoadModulesForEnabledPlugins() [d:\build\++ue4\sync\engine\source\runtime\projects\private\pluginmanager.cpp:986]
UE4Editor!FEngineLoop::Init() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:2881]
UE4Editor_UnrealEd!EditorInit() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedglobals.cpp:76]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:150]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:144]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:223]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll

**Comment by mrkriv** [comment]
Hello!

Error occurs when calling the method
UnrealEngine.NativeManager.GetGameLogicAssemblyName
This method should return the C# build with game logic.

There may be several reasons
First, the project itself should be built **/Plugins/UnrealDotNet/Source/UnrealEngineSharp**

Then you should check that in the folder **Plugins\UnrealDotNet\Binaries\Win64\dotenet_libs**
there is a library **Newtonsoft.Json.dll**

in addition, here you can see that I was lazy and the name of the native build is just written here
https://github.com/mrkriv/UnrealDotNet/blob/master/Plugins/UnrealDotNet/Source/UnrealEngineSharp/NativeManager.cs#L15

but most importantly, in the current state, this project shut not be used in production.

**Comment by menghuijinxi** [comment]
Thank you, although I still can't open it.

**Comment by mrkriv** [comment]
Try to change here
https://github.com/mrkriv/UnrealDotNet/blob/master/Plugins/UnrealDotNet/Source/UnrealEngineSharp/NativeManager.cs#L17

this:

> UE4Editor-UnrealDotNetRuntime-Win64-DebugGame

on this:

> UE4Editor-UnrealDotNetRuntime

and then rebuild GameLogic.sln

If this does not help, here is the archive with the plugin assembled and configured for 4.20
https://yadi.sk/d/JZxZwDNMdVK9BA

**Comment by menghuijinxi** [comment]
Thank you, can open it.
